slogan: "Yet another bootstrap theme."

theme: cerulean
inverse: inverse

menu:
  - title: 归档
    url: archives
    intro: "所有文章归档"
    icon: "fa fa-archive"
  - title: 分类
    url: categories
    intro: "所有文章分类"
    icon: "fa fa-folder"
  - title: 标签
    url: tags
    intro: "标签"
    icon: "fa fa-tags"
  - title: 关于我
    url: about
    intro: "关于我"
    icon: "fa fa-user"
  - title: 相册
    url: photo
    intro: "相册"
    icon: "fa fa-user"




links:
  - title: "Hexo"
    url: http://hexo.io
    intro: "My Linkin account."
    icon: "fa fa-share"
  - title: "我的github"
    url:
    intro: "My Github account."
    icon: "fa fa-github"


widgets:
- search
- category
- tagcloud
- recent_posts
- links


rss: atom.xml
fancybox: true
favicon: favicon.ico
duoshuo_shortname: clockbone

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
swiftype_key:

# share widgets
bdshare:
jiathis: true


