menu:
  首页: /
  归档: /archives
  关于: /about

widgets: #站点右边栏
- search
- category
- tagcloud  #标签云
- intro
- weibo    #新浪微博秀
- blogroll    #友情链接

excerpt_link: 阅读全文 #替换为中文

plugins: 
- hexo-generator-feed

twitter: #右边栏要显示twitter展示的话，需要在此设置
  username:
  show_replies: false
  tweet_count: 5

addthis:  #SNS分享，身在天朝，当然用“百度分享”，暂时默认
  enable: true
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true  #图片效果，默认

google_analytics: 
rss:

comment_provider: facebook
# Facebook comment
facebook:
  appid: 123456789012345
  comment_count: 5
  comment_width: 840
  comment_colorscheme: light
